# Generated by Django 5.2.8 on 2025-12-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0004_review_review_user_alter_review_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='av_ratting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_ratting',
            field=models.IntegerField(default=0),
        ),
    ]
